"""init

Revision ID: 0346aca07ed5
Revises: 156b0573e3ac
Create Date: 2026-05-29 07:11:43.448621

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0346aca07ed5"
down_revision: Union[str, Sequence[str], None] = "156b0573e3ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
