"""init

Revision ID: 156b0573e3ac
Revises: cca9c7a50675
Create Date: 2026-05-29 07:07:13.126154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "156b0573e3ac"
down_revision: Union[str, Sequence[str], None] = "cca9c7a50675"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("line1", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("postal_code", sa.String(length=25), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_employee_id"), "addresses", ["employee_id"], unique=False)
    op.create_index(op.f("ix_addresses_id"), "addresses", ["id"], unique=False)
    op.drop_index(op.f("ix_Address_employee_id"), table_name="Address")
    op.drop_index(op.f("ix_Address_id"), table_name="Address")
    op.drop_table("Address")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Address",
        sa.Column("line1", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("city", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("postal_code", sa.VARCHAR(length=25), autoincrement=False, nullable=True),
        sa.Column("country", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"], ["employees.id"], name=op.f("Address_employee_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Address_pkey")),
    )
    op.create_index(op.f("ix_Address_id"), "Address", ["id"], unique=False)
    op.create_index(op.f("ix_Address_employee_id"), "Address", ["employee_id"], unique=False)
    op.drop_index(op.f("ix_addresses_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_employee_id"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
