"""add column password

Revision ID: 1b0869a04591
Revises: 0346aca07ed5
Create Date: 2026-05-29 16:00:31.790558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0869a04591'
down_revision: Union[str, Sequence[str], None] = '0346aca07ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.execute("Update employees Set password_hash = 'placeholder' where password_hash is null")
    op.alter_column("employees","password_hash",nullable = False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###
