"""init

Revision ID: 2d99cbaf54d8
Revises: 661e5e082ce4
Create Date: 2026-05-28 17:23:16.780729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d99cbaf54d8"
down_revision: Union[str, Sequence[str], None] = "661e5e082ce4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Address",
        sa.Column("line1", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("postal_code", sa.String(length=25), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city"),
    )
    op.create_index(op.f("ix_Address_id"), "Address", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Address_id"), table_name="Address")
    op.drop_table("Address")
    # ### end Alembic commands ###
