"""Add EmployeeRole

Revision ID: 4978a5c37e54
Revises: 478b2e141732
Create Date: 2026-06-01 14:13:30.788481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum


# revision identifiers, used by Alembic.
revision: str = '4978a5c37e54'
down_revision: Union[str, Sequence[str], None] = '478b2e141732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM = sa.Enum('UI', 'UX', 'DEVOLOPER', 'HR', name='employeerole')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    op.add_column('employees', sa.Column("role", _ROLE_ENUM, server_default='DEVOLOPER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
