"""init

Revision ID: d9b40995409b
Revises: 30dfd24bf28f
Create Date: 2026-05-28 17:39:13.093252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b40995409b'
down_revision: Union[str, Sequence[str], None] = '30dfd24bf28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Address_city_key'), 'Address', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('Address_city_key'), 'Address', ['city'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
