"""init

Revision ID: eac57364f3d6
Revises: 2d99cbaf54d8
Create Date: 2026-05-28 17:30:13.024891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac57364f3d6'
down_revision: Union[str, Sequence[str], None] = '2d99cbaf54d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Address', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Address_employee_id'), 'Address', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'Address', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Address', type_='foreignkey')
    op.drop_index(op.f('ix_Address_employee_id'), table_name='Address')
    op.drop_column('Address', 'employee_id')
    # ### end Alembic commands ###
